title: <p align="center"> Santosh Krishnan </p>
logo: /assets/img/MyPic.jpg
description: 
   <p align="center">
   <a href="./Resume.pdf">Resume</a> |
   <a href="https://www.linkedin.com/in/santosh-krishnan-609947161/">LinkedIn</a> |
   <a href="https://github.com/skorn-g12/">GitHub</a>

theme: jekyll-theme-minimal
